version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount the application code for development (optional, remove for production-like build)
      # This allows code changes to be reflected without rebuilding the image.
      - ./backend/app:/app/app 
      # Mount the SQLite database file to persist data outside the container
      - ./backend/test.db:/app/test.db 
    env_file:
      # Pass environment variables from a .env file
      # Ensure your .env file is in the same directory as docker-compose.yml
      # and contains OPENAI_API_KEY and DATABASE_URL (if different from default)
      - .env 
    # environment:
      # Alternatively, set environment variables directly:
      # - OPENAI_API_KEY=${OPENAI_API_KEY} 
      # - DATABASE_URL=sqlite:///./test.db # Ensure this path is accessible inside the container
