name: Docker Compose CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test_with_docker_compose:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend_2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          echo "Docker version: $(docker --version)"
          echo "Docker Compose version: $(docker compose version)"

      - name: Build and run services
        run: docker compose up --build --remove-orphans -d --wait

      - name: Install pytest in the api container
        run: docker compose exec -T api pip install pytest pytest-asyncio

      - name: Run tests in the api container
        run: docker compose exec -T api python -m pytest

      - name: Stop and remove containers
        if: always()
        run: docker compose down --remove-orphans
