name: Python CI

on:
  push:
    branches: [ main, master, develop ] # Adjust branches as needed
  pull_request:
    branches: [ main, master, develop ] # Adjust branches as needed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # Specify Python versions to test against

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv and dependencies
      working-directory: ./backend # Ensure commands run in the backend directory context
      run: |
        python -m pip install --upgrade pip uv
        uv pip install -r requirements.txt
        uv pip install ruff pytest pytest-asyncio 
      # Install linting and testing tools

    - name: Lint with Ruff
      working-directory: ./backend
      run: |
        ruff check .

    - name: Run tests with Pytest
      working-directory: ./backend
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Make API key available to tests
        DATABASE_URL: "sqlite:///./test_ci.db" # Use a CI-specific database
      run: |
        pytest
